package com.code.immersivemode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private int record_id;
    private int user_id;
    private String record_time;

    public Record() {
    }

    public Record(int record_id) {
        this.record_id = record_id;
    }

    public Record(int record_id, int user_id, String record_time) {
        this.record_id = record_id;
        this.user_id = user_id;
        this.record_time = record_time;
    }

    public int getRecord_id() {
        return record_id;
    }

    public void setRecord_id(int record_id) {
        this.record_id = record_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public String getRecord_time() {
        return record_time;
    }

    public void setRecord_time(String record_time) {
        this.record_time = record_time;
    }

}
