package com.code.immersivemode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    private int user_id;
    private java.util.Date record_time;
    private Integer time;
    private Integer step;
    private Double distance;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, int user_id, java.util.Date record_time, Integer time, Integer step, Double distance) {
        this.id = id;
        this.user_id = user_id;
        this.record_time = record_time;
        this.time = time;
        this.step = step;
        this.distance = distance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public java.util.Date getRecord_time() {
        return record_time;
    }

    public void setRecord_time(java.util.Date record_time) {
        this.record_time = record_time;
    }

    public Integer getTime() {
        return time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    public Integer getStep() {
        return step;
    }

    public void setStep(Integer step) {
        this.step = step;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

}
