package com.code.immersivemode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    private int user_id;
    private java.util.Date record_time;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, int user_id, java.util.Date record_time) {
        this.id = id;
        this.user_id = user_id;
        this.record_time = record_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public java.util.Date getRecord_time() {
        return record_time;
    }

    public void setRecord_time(java.util.Date record_time) {
        this.record_time = record_time;
    }

}
