package com.code.immersivemode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STEP.
 */
public class Step {

    private Long id;
    private Integer user_id;
    private String step_date;
    private Integer step_0;
    private Integer step_1;
    private Integer step_2;
    private Integer step_3;
    private Integer step_4;
    private Integer step_5;
    private Integer step_6;
    private Integer step_7;
    private Integer step_8;
    private Integer step_9;
    private Integer step_10;
    private Integer step_11;
    private Integer step_12;
    private Integer step_13;
    private Integer step_14;
    private Integer step_15;
    private Integer step_16;
    private Integer step_17;
    private Integer step_18;
    private Integer step_19;
    private Integer step_20;
    private Integer step_21;
    private Integer step_22;
    private Integer step_23;

    public Step() {
    }

    public Step(Long id) {
        this.id = id;
    }

    public Step(Long id, Integer user_id, String step_date, Integer step_0, Integer step_1, Integer step_2, Integer step_3, Integer step_4, Integer step_5, Integer step_6, Integer step_7, Integer step_8, Integer step_9, Integer step_10, Integer step_11, Integer step_12, Integer step_13, Integer step_14, Integer step_15, Integer step_16, Integer step_17, Integer step_18, Integer step_19, Integer step_20, Integer step_21, Integer step_22, Integer step_23) {
        this.id = id;
        this.user_id = user_id;
        this.step_date = step_date;
        this.step_0 = step_0;
        this.step_1 = step_1;
        this.step_2 = step_2;
        this.step_3 = step_3;
        this.step_4 = step_4;
        this.step_5 = step_5;
        this.step_6 = step_6;
        this.step_7 = step_7;
        this.step_8 = step_8;
        this.step_9 = step_9;
        this.step_10 = step_10;
        this.step_11 = step_11;
        this.step_12 = step_12;
        this.step_13 = step_13;
        this.step_14 = step_14;
        this.step_15 = step_15;
        this.step_16 = step_16;
        this.step_17 = step_17;
        this.step_18 = step_18;
        this.step_19 = step_19;
        this.step_20 = step_20;
        this.step_21 = step_21;
        this.step_22 = step_22;
        this.step_23 = step_23;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getStep_date() {
        return step_date;
    }

    public void setStep_date(String step_date) {
        this.step_date = step_date;
    }

    public Integer getStep_0() {
        return step_0;
    }

    public void setStep_0(Integer step_0) {
        this.step_0 = step_0;
    }

    public Integer getStep_1() {
        return step_1;
    }

    public void setStep_1(Integer step_1) {
        this.step_1 = step_1;
    }

    public Integer getStep_2() {
        return step_2;
    }

    public void setStep_2(Integer step_2) {
        this.step_2 = step_2;
    }

    public Integer getStep_3() {
        return step_3;
    }

    public void setStep_3(Integer step_3) {
        this.step_3 = step_3;
    }

    public Integer getStep_4() {
        return step_4;
    }

    public void setStep_4(Integer step_4) {
        this.step_4 = step_4;
    }

    public Integer getStep_5() {
        return step_5;
    }

    public void setStep_5(Integer step_5) {
        this.step_5 = step_5;
    }

    public Integer getStep_6() {
        return step_6;
    }

    public void setStep_6(Integer step_6) {
        this.step_6 = step_6;
    }

    public Integer getStep_7() {
        return step_7;
    }

    public void setStep_7(Integer step_7) {
        this.step_7 = step_7;
    }

    public Integer getStep_8() {
        return step_8;
    }

    public void setStep_8(Integer step_8) {
        this.step_8 = step_8;
    }

    public Integer getStep_9() {
        return step_9;
    }

    public void setStep_9(Integer step_9) {
        this.step_9 = step_9;
    }

    public Integer getStep_10() {
        return step_10;
    }

    public void setStep_10(Integer step_10) {
        this.step_10 = step_10;
    }

    public Integer getStep_11() {
        return step_11;
    }

    public void setStep_11(Integer step_11) {
        this.step_11 = step_11;
    }

    public Integer getStep_12() {
        return step_12;
    }

    public void setStep_12(Integer step_12) {
        this.step_12 = step_12;
    }

    public Integer getStep_13() {
        return step_13;
    }

    public void setStep_13(Integer step_13) {
        this.step_13 = step_13;
    }

    public Integer getStep_14() {
        return step_14;
    }

    public void setStep_14(Integer step_14) {
        this.step_14 = step_14;
    }

    public Integer getStep_15() {
        return step_15;
    }

    public void setStep_15(Integer step_15) {
        this.step_15 = step_15;
    }

    public Integer getStep_16() {
        return step_16;
    }

    public void setStep_16(Integer step_16) {
        this.step_16 = step_16;
    }

    public Integer getStep_17() {
        return step_17;
    }

    public void setStep_17(Integer step_17) {
        this.step_17 = step_17;
    }

    public Integer getStep_18() {
        return step_18;
    }

    public void setStep_18(Integer step_18) {
        this.step_18 = step_18;
    }

    public Integer getStep_19() {
        return step_19;
    }

    public void setStep_19(Integer step_19) {
        this.step_19 = step_19;
    }

    public Integer getStep_20() {
        return step_20;
    }

    public void setStep_20(Integer step_20) {
        this.step_20 = step_20;
    }

    public Integer getStep_21() {
        return step_21;
    }

    public void setStep_21(Integer step_21) {
        this.step_21 = step_21;
    }

    public Integer getStep_22() {
        return step_22;
    }

    public void setStep_22(Integer step_22) {
        this.step_22 = step_22;
    }

    public Integer getStep_23() {
        return step_23;
    }

    public void setStep_23(Integer step_23) {
        this.step_23 = step_23;
    }

}
