package com.code.immersivemode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String password;
    private String birthday;
    private String name;
    private Integer gender;
    private String weight;
    private String height;
    private Integer sum_step;
    private Integer sum_calorie;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String email, String password, String birthday, String name, Integer gender, String weight, String height, Integer sum_step, Integer sum_calorie) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.birthday = birthday;
        this.name = name;
        this.gender = gender;
        this.weight = weight;
        this.height = height;
        this.sum_step = sum_step;
        this.sum_calorie = sum_calorie;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public Integer getSum_step() {
        return sum_step;
    }

    public void setSum_step(Integer sum_step) {
        this.sum_step = sum_step;
    }

    public Integer getSum_calorie() {
        return sum_calorie;
    }

    public void setSum_calorie(Integer sum_calorie) {
        this.sum_calorie = sum_calorie;
    }

}
